export default {
    // Register
    register_upload_type_licence: 'Tipo de licencia',
    register_upload_driver_licence: 'Licencia de conducir',
    register_upload_criminal_record: 'Certificado de antecedentes',
    register_upload_id_card: 'Cedula de identidad',
    register_upload_photo_driver: 'Foto de conductor',
    register_add_new_vehicle: 'Agregar nuevo vehiculo',
    // Headers
    offer_list_header: 'Inicio',
    payment_information_header: 'Informacion pagos',
    finish_trip_header: 'Termino del viaje',
    my_vehicles_header: 'Mis vehiculos',
    // vehiculo
    add_new_vehicle: 'Agregar un nuevo vehiculo',
    licence_plate: 'Patente',
    year: 'Ano',
    type: 'Tipo',
    vehicle_roll: 'Padron del vehiculo',
    annotation_certificate: 'Certificado de anotaciones',
    photo_authorization: 'Foto de autorizacion de conductor',
    photo_vehicle: 'Foto de vehiculo',
    permission_to_circulate: 'Foto de permiso de circulacion',
    car_make: 'Marca',
    model: 'Modelo',
    add_vehicle: 'Agregar Vehiculo',
    // Cards
    add_card: 'Agregar nueva tarjeta',
    no_cards_message: 'Registra tu tarjeta y realiza tus pagos',
    no_cards_title: 'Aun no hay tarjetas',
    expiration_date: 'Fecha de expiracion',
    cvv: 'Codigo de seguridad',
    card_number: 'Numero de tarjeta',
    holder: 'Titular(Nombre en la tarjeta)',
    delete_card_alert: 'Seguro que deseas borrar la tarjeta',
    warning_add_card: 'Por tu seguridad, te cobraremos un monto aleatorio de menos 1200 para verificar que la tarjeta se valida',
    // Tutorial
    tutorial_money_title: 'Ofrezca su tarifa para el viaje',
    tutorial_fast_title: 'Transporta rapido',
    tutorial_offer_title: '¿Tienes un auto? ¡Gana dinero!',
    tutorial_money_subtitle: 'Ingrese la ruta y configure su tarifa, se la ofrecemos a los conductores',
    tutorial_fast_subtitle: 'Las solicitudes de transporte se ofrecen a los conductores cercanos',
    tutorial_offer_subtitle: 'Descarga la aplicacion para conductores',
    // Vieja
    from: 'De:',
    to: 'A: ',
    driver: 'Tu viaje con',
    money: 'CLP $',
    date: 'Fecha ',
    // Modals
    send_offer: 'Enviando oferta a conductores',
    accept_offer_driver: 'Esperando oferta de conductores',
    cancel_trip: 'Cancelando el viaje, espere',
    end_trip: 'Terminando viaje, espere',
    profile_edit: 'Editando perfil',
    sent_data: 'Enviado correctamente',
    sent_data_fail: 'Error: Intentalo nuevamente',
    share: 'Compartelo con amigos',
    alert: '¡Alerta!',
    // Botones tipicos
    button_cancel: 'CANCELAR',
    button_accept: 'ACEPTAR',
    button_update: 'ACTUALIZAR',
    button_continue: 'CONTINUAR',
    button_come_back: 'VOLVER',
    button_update_price: 'ACTUALIZAR PRECIO',
    // oferta
    height: 'Alto (cm)',
    width: 'Ancho (cm)',
    long: 'Largo (cm)',
    description: 'Descripcion',
    offer_price: 'Precio a ofrecer',
    payment_type: 'Forma de pago',
    weight: 'Peso aprox. de la carga',
    dimensions_error: 'Error: deben ser numeros mayores a 0',
    price_error: 'Error: deben ser mayor a 1000',
    price_option_error: 'Debe escoger al menos una',
    description_error: 'Error: obligatorio',
    aditional_help:'Necesitaras ayuda adicional para cargar?',
    driver_help:'Necesitaras ayuda del chofer para cargar?',
    rider_help:'Ayudaras en el flete?',
    rider_travel:'Viajaras en el vehiculo?',
    // comunes
    required_field: '*Campo requerido',
    //
    verification_title: "Verificación",
    verification_text: "Ingresa el código de verificación enviado al número de móvil que has ingresado",
    verification_placeholder: "-",
    verify_mobile:'Verificar y continuar',
    cancel_button: 'Cancelar',
    accept_button: 'Aceptar',
    confirm_button: 'Confirmar',
    email_placeholder :"Email",
    terminos_condiciones_link: "Acepto terminos y condiciones",
    terminos_condiciones: "terminos y condiciones y todo lo relacionado",
    upload_photo: "Agregar foto de perfil ",
    terminos_condiciones_titulo: "Terminos y condiciones",
    password_placeholder:"Contraseña",
    movil_no_placeholder: 'Movil',
    login_button:"Iniciar sesion",
    register_link:"Registrarse",
    forgot_password_link:"Recuperar contraseña",
    facebook_login_button:'Iniciar sesión Facebook.',
    password_blank_messege:'Contraseña no puede estar vacia.',
    password_alphaNumeric_check:'La contraseña debe tener al menos un carácter alfanumérico y una longitud de 8-15 caracteres.',
    password_complexity_check:'La contraseña debe tener almenos una minúscula, una mayúscula, 1 número, 1 carácter especial y tener entre 6-10 caracteres de longitud',
    valid_email_check:'Por favor ingrese un correo válido.',
    movil_no_blank_error: 'Por favor ingrese un numero de telefono',
    facebook_login_error:'Usted ya posee una cuenta con este correo. Por favor ingrese con su correo y contraseña.',
    forgot_password_success_messege:'Se ha enviado un link a su correo para reiniciar su contraseña. Por favor revise y cambie su contraseña.',
    facebook_login_auth_error:'Error de acceso a Facebook',
    static_notification_title:'Notificación GrabCab ',
    refferal_code_validation_modal:'Validando tu código de referido...',
    refferal_id_not_match_error:'Este no es un ID de referidos válido.',
    registration_title:'Registro',
    registration_user: 'Datos usuario',
    registration_driver: 'Datos Conductor',
    registration_vehicle: 'Datos Vehiculo',
    first_name_placeholder:'Nombre*',
    first_name_blank_error:"Por favor ingrese su nombre.",
    last_name_placeholder:'Apellidos*',
    last_name_blank_error:'Por favor ingrese sus apellidos.',
    rut_placeholder:'Rut*',
    rut_blank_error:"Por favor ingrese su rut.",
    mobile_no_placeholder:'Número de teléfono*',
    mobile_no_blank_error:'Por favor ingrese un número de teléfono válido.',
    confirm_password_placeholder:'Confirme su contraseña*',
    confirm_password_not_match_err:'La contraseña no coincide',
    referral_id_placeholder:'Id de referido (opcional)',
    register_button:'Continuar',
    edit_button: 'Guardar cambios',
    come_back_button: 'Volver',
    email_exist_error:'El correo ingresado ya está asociado a una cuenta.',
    Account_linking_error:'Error de enlace de cuentas',
    send_email_button:'Enviar email',
    // menu
    book_your_ride_menu:'Agende su viaje',
    profile_setting_menu:'Ajustes de perfil',
    offer_list_menu: 'Ofertas de viajes',
    payment_information_menu: 'Datos de pago',
    my_wallet_menu:'Mi billetera',
    my_rides_menu:'Mis viajes',
    my_vehicles_menu: 'Mis vehiculos',
    about_us_menu:'Acerca de nosotros',
    //
    cardsSettings: 'Configuracion de pago',
    logout:'Cerrar sesión',
    photo_upload_action_sheet_title:'Elige un medio',
    camera:'Cámara',
    galery:'Galería',
    cancel:'Cancelar',
    yes:'Sí',
    network_request_failed:'Solicitud de red fallida',
    password_update_messege:'Su contraseña se ha actualizado correctamente',
    delete_account_modal_title:'Confirmar',
    delete_account_modal_subtitle:'¿Quiere eliminar su cuenta?',
    profile_page_title:'Mi perfil',
    my_wallet_title:'Saldo de mi billetera',
    profile_page_subtitle:'Detalles de perfil',
    location_lebel:'Ubicación',
    language_lebel:'Idioma',
    preffer_language:'Español',
    change_password_lebel:'Cambiar contraseña',
    delete_account_lebel:'Eliminar cuenta',
    change_password_modal_title:'¿Cambiar contraseña?',
    old_password_placeholder:'Contraseña anterior',
    new_password_placeholder:'Nueva contraseña',
    old_password_validation_error:'Por favor ingrese la contraseña anterior correctamente',
    new_password_validation_error:'Por favor ingrese una nueva contraseña',
    update_button:'Actualizar',
    update_profile_title:'Actualizar perfil',
    map_screen_where_input_text:'Desde dónde?',
    map_screen_drop_input_text:'Hasta dónde ?',
    driver_finding_alert:'Buscando conductores para tí',
    no_driver_found_alert_title:'Alerta!',
    no_driver_found_alert_messege:'Lo sentimos, no se han encontrado conductores en este momento. Por favor reintente después.',
    no_driver_found_alert_OK_button:'OK',
    no_driver_found_alert_TRY_AGAIN_button:'Intentar nuevamente',
    pickup_and_drop_location_blank_error:'Seleccione ubicación de recogida y de destino.',
    pickup_location_blank_error:'Seleccione ubicación de recogida',
    drop_location_blank_error:'Sellecione ubicación de destino',
    car_type_blank_error:'Seleccione tipo de vehiculo',
    congratulation:'Felicitaciones!',
    refferal_bonus_messege_text:'Tu bonus de referidos -',
    map_screen_title:'Tomar mi vehiculo',
    cab_selection_title:'Elige tu vehículo',
    cab_selection_subtitle:'Presiona para seleccionar el tipo de vehículo y agendar.',
    not_available:'No disponible',
    book_now_button:'Agendar',
    contact_details:'Detalles de contacto',
    phone:'Teléfono',
    my_wallet_tile:'Mi billetera',
    wallet_ballance:'Saldo de mi billetera ',
    add_money:'Añadir fondos',
    transaction_history_title:'Historial de transacciones',
    successfully:'Exitosamente',
    form_wallet:'Formulario de pago ',
    Transaction_Id :'Id de transacción',
    ride_list_title:'Mis viajes',
    no_car_assign_text:'No hay vehículo asignado ',
    not_found_text:'No encontrado',
    ride_details_page_title:'Detalles de mis viajes',
    you_rated_text:'Usted calificó',
    car_no_not_found:'Número de vehículo no encontrado',
    track_now_button:'Hacer seguimiento',
    bill_details_title:'Detalles de factura',
    your_trip:'Tu viaje',
    discount:'Descuento',
    promo_apply:'(Aplica promoción)',
    grand_total:'Total',
    payment_status:'Estado del pago',
    paynow_button:'Pagar ahora',
    call_driver:'Llamar conductores',
    booked_cab_title:'Vehículo agendado',
    you_selected:'Usted seleccionó -',
    otp:'OTP :',
    driver_assign_messege:'El conductor se asignará pronto...',
    cancel_ride:'Cancelar viaje',
    rider_cancel_text:'Cancelar viaje',
    cancel_messege1:'Tu viaje con Id de agendamiento',
    cancel_messege2:'Ha sido cancelado exitosamente',
    dont_cancel_text:'No cancelar',
    cancel_reason_modal_title:'Cuál es la razón de cancelamiento',
    chat_title:'Chat',
    send_button_text:'Enviar',
    chat_input_title:'Escriba algo amable...',
    chat_not_found:'No se encontró historial de chat',
    card_payment_blank_error:'Por favor llene todos los detalles apropiadamente.',
    payment_amound_error:'El monto a pagar es muy bajo.',
    invalid_card_details_error:'La tarjeta no es válida.',
    success_payment:'Pago exitoso',
    confrimation:'Confirmación',
    payment_alert:'¿Quiere eliminar su tarjeta?',
    please_wait:'Porfavor espere...',
    enterCVV:'Por favor ingrese su CVV de su tarjeta',
    your_promo:'Tu promoción',
    promo_exp:'Lo sentimos \n El código de promoción ha expirado o ha alcanzado su límite de usos',
    promo_limit:'Lo sentimos \n límite de usos de la promoción sobrepasados.',
    promo_eligiblity:'Lo sentimos \n Usted no es elegible para esta promoción.',
    payment:'Pago',
    bill_details:'Detalles de factura',
    apply_promo:'Aplicar promoción',
    your_fare:'Su tarifa',
    promo_discount:'Descuento promocional',
    wallet_discount:'Descuento de billetera',
    payable_ammount:'Monto a pagar',
    use_wallet_balance:'Usar saldo de billetera ( Tu balance - ',
    pay_cash:'Pagar con efectivo',
    pay_card:'Pagar con tarjeta',
    proceed_pay:'Proceder al pago',
    save_card:'Tus tarjetas guardadas',
    thanks:'Gracias por calificar',
    skip:'saltar',
    receipt:'Recibo',
    rate_ride:'POR FAVOR CALIFICA TU VIAJE',
    err:'Error!',
    route_not_found:'No se encuentra ninguna ruta',
    sorry:'Lo sentimos',
    multipleBooking:'Grabcab actualmente no soporta múltiples reservas.',
    driver_not_found:'No podemos asignar al conductor en este momento. Contacte al administrador !!',
    new_booking_request_push_notification:'Tienes una nueva solicitud de reserva',
    fare_details:'Detalles de tarifa',
    base_fare:'tarifa base',
    convenience_free:'Comisiones convenientes',
    total_fare:'Tarifa total',
    inclusive_tax:'(Incluye impuestos)',
    nb:'Importante: Tu tarifa aumentará si hay peajes, cambios de ruta y destino o si el viaje tomó más tiempo por tráfico u otros factores',
    confrim_booking:'Confirmar reserva',
    estimate_fare_text:'Este es solo tu tarifa estimada',
    done:'Hecho',
    notification_headerText:'Notificación',
    notification_not_found:'No se encontró ninguna notificación',
    track_cab:'Haz seguimiento del vehículo',
    location_permission:'Dar acceso a ubicación',
    ask_me_later:'Preguntarme después',
    min_order_value:'Valor de orden mínimo-'

}
