// Modals
export const SHOW_MODAL_RESET_PASSWORD = 'SHOW_MODAL_RESET_PASSWORD';
export const HIDE_MODAL_RESET_PASSWORD = 'HIDE_MODAL_RESET_PASSWORD';
export const SHOW_MODAL_CHECK = 'SHOW_MODAL_CHECK';
export const HIDE_MODAL_CHECK = 'HIDE_MODAL_CHECK';
export const SHOW_MODAL_SOCIAL = 'SHOW_MODAL_SOCIAL';
export const HIDE_MODAL_SOCIAL = 'HIDE_MODAL_SOCIAL';

//Auth const
export const SIGNUP_USER = 'signup_user';
export const SIGNUP_USER_SUCCESS = 'signup_user_success';
export const SIGNUP_USER_FAILED = 'signup_user_failed';
export const SIGNIN_USER = 'signin_user';
export const SIGNIN_USER_SUCCESS = 'signin_user_success';
export const SIGNIN_USER_FAILED = 'signin_user_failed';
export const SIGNOUT_USER = 'signout_user';
export const SIGNOUT_USER_SUCCESS = 'signout_user_success';
export const SIGNOUT_USER_FAILED = 'signout_user_failed';
// recuperar contrasena
export const RESETTING_PASSWORD_SUCCESS = 'resetting_password_success';
export const RESETTING_PASSWORD = 'resetting_password';
export const RESETTING_PASSWORD_FAILED = 'resetting_password_failed';
// Cards
export const CARD_LOAD= 'CARD_LOAD';
export const CARD_LOAD_FAILED = 'CARD_LOAD_FAILED';
export const CARD_LOADED = 'CARD_LOADED';
export const CARD_ADDED = 'CARD_ADDED';
export const CARD_ADD = 'CARD_ADD';
export const CARD_ADD_FAILED = 'CARD_ADD_FAILED';
export const CARD_DELETED = 'CARD_DELETED';
export const CARD_DELETE = 'CARD_DELETE';
export const CARD_DELETE_FAILED = 'CARD_DELETE_FAILED';
export const CARD_CLEAN= 'CARD_CLEAN';
// Consultas
export const CONSULTAS_ADD = 'CONSULTAS_ADD';
export const CONSULTAS_LOANDING = 'CONSULTAS_LOANDING';
export const CONSULTAS_UPDATE_LOANDING = 'CONSULTAS_UPDATE_LOANDING';
export const CONSULTAS_UPDATE = 'CONSULTAS_UPDATE';
export const CONSULTAS_FAILED = 'CONSULTAS_FAILED';
// Ofertas
export const OFERTAS_ADDED = 'OFERTAS_ADDED';
export const OFERTAS_ADD = 'OFERTAS_ADD';
export const OFERTAS_ADD_FAILED = 'OFERTAS_ADD_FAILED';
export const OFERTAS_UPDATED = 'OFERTAS_UPDATED';
export const OFERTAS_UPDATE = 'OFERTAS_UPDATE';
export const OFERTAS_UPDATE_FAILED = 'OFERTAS_UPDATE_FAILED';
export const OFERTAS_CLEAN = 'OFERTAS_CLEAN';
export const OFERTAS_CANCEL = 'OFERTAS_CANCEL';
export const OFERTAS_CANCELED = 'OFERTAS_CANCELED';
export const OFERTAS_CANCEL_FAILED = 'OFERTAS_CANCEL_FAILED';

// Contraofertas
export const CONTRAOFERTAS_LOAD= 'CONTRAOFERTAS_LOAD';
export const CONTRAOFERTAS_LOAD_FAILED = 'CONTRAOFERTAS_LOAD_FAILED';
export const CONTRAOFERTAS_LOADED = 'CONTRAOFERTAS_LOADED';
export const CONTRAOFERTAS_DECLINE= 'CONTRAOFERTAS_DECLINE';
export const CONTRAOFERTAS_DECLINED= 'CONTRAOFERTAS_DECLINED';
export const CONTRAOFERTAS_DECLINE_FAILED= 'CONTRAOFERTAS_DECLINE_FAILED';
export const CONTRAOFERTAS_ACCEPT= 'CONTRAOFERTAS_ACCEPT';
export const CONTRAOFERTAS_ACCEPTED= 'CONTRAOFERTAS_ACCEPTED';
export const CONTRAOFERTAS_ACCEPT_FAILED= 'CONTRAOFERTAS_ACCEPT_FAILED';
export const CONTRAOFERTAS_CLEAN = 'CONTRAOFERTAS_CLEAN';
export const CONTRAOFERTAS_STOP_LOAD = 'CONTRAOFERTAS_STOP_LOAD';

//Perfil
export const PERFIL_LOAD = 'PERFIL_LOAD';
export const PERFIL_LOADED = 'PERFIL_LOADED';
export const PERFIL_UPDATE = 'PERFIL_UPDATE';
export const PERFIL_UPDATED = 'PERFIL_UPDATED';
export const PERFIL_LOAD_FAILED = 'PERFIL_LOAD_FAILED';
export const PERFIL_UPDATE_FAILED = 'PERFIL_UPDATE_FAILED';
export const PERFIL_CLEAN = 'PERFIL_CLEAN';
// Posicion
export const POSICION_ADD = 'POSICION_ADD';
export const POSICION_LOANDING = 'POSICION_LOANDING';
export const POSICION_UPDATE_LOANDING = 'POSICION_UPDATE_LOANDING';
export const POSICION_UPDATE = 'POSICION_UPDATE';
export const POSICION_FAILED = 'POSICION_FAILED';
export const POSICION_CLEAN = 'POSICION_CLEAN';
// Pagos
export const PAGOS_ADD = 'PAGOS_ADD';
export const PAGOS_LOANDING = 'PAGOS_LOANDING';
export const PAGOS_FAILED = 'PAGOS_FAILED';
export const PAGOS_CLEAN = 'PAGOS_CLEAN';
// Viajes
export const VIAJES_LOADED = 'VIAJES_LOADED';
export const VIAJES_LOAD = 'VIAJES_LOAD';
export const VIAJES_LOAD_FAILED = 'VIAJES_LOAD_FAILED';
export const VIAJE_CURRENCY_LOADED = 'VIAJE_CURRENCY_LOADED';
export const VIAJE_CURRENCY_LOAD = 'VIAJE_CURRENCY_LOAD';
export const VIAJE_CURRENCY_LOAD_FAILED = 'VIAJE_CURRENCY_LOAD_FAILED';
export const VIAJES_UPDATED = 'VIAJES_UPDATED';
export const VIAJES_UPDATE = 'VIAJES_UPDATE';
export const VIAJES_UPDATE_FAILED = 'VIAJES_UPDATE_FAILED';
export const VIAJE_END = 'VIAJE_END';
export const VIAJE_ENDED = 'VIAJE_ENDED';
export const VIAJE_END_FAILED = 'VIAJE_END_FAILED';
export const VIAJES_CLEAN = 'VIAJES_CLEAN';
// ABOUT
export const ABOUT_LOADED = 'ABOUT_LOADED';
export const ABOUT_LOAD = 'ABOUT_LOAD';
export const ABOUT_LOAD_FAILED = 'ABOUT_LOAD_FAILED';
export const ABOUT_CLEAN = 'ABOUT_CLEAN';
// SANCIONES
export const SANCIONES_ADD = 'SANCIONES_ADD';
export const SANCIONES_LOANDING = 'SANCIONES_LOANDING';
export const SANCIONES_UPDATE_LOANDING = 'SANCIONES_UPDATE_LOANDING';
export const SANCIONES_UPDATE = 'SANCIONES_UPDATE';
export const SANCIONES_FAILED = 'SANCIONES_FAILED';
