// Modals
export const SHOW_MODAL_RESET_PASSWORD = 'SHOW_MODAL_RESET_PASSWORD';
export const HIDE_MODAL_RESET_PASSWORD = 'HIDE_MODAL_RESET_PASSWORD';
export const SHOW_MODAL_CHECK = 'SHOW_MODAL_CHECK';
export const HIDE_MODAL_CHECK = 'HIDE_MODAL_CHECK';
export const SHOW_MODAL_SOCIAL = 'SHOW_MODAL_SOCIAL';
export const HIDE_MODAL_SOCIAL = 'HIDE_MODAL_SOCIAL';
//Auth const
export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_FAILED = 'SIGN_UP_USER_FAILED';
export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS';
export const SIGN_IN_USER_FAILED = 'SIGN_IN_USER_FAILED';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
export const SIGN_OUT_USER_SUCCESS = 'SIGN_OUT_USER_SUCCESS';
export const SIGN_OUT_USER_FAILED = 'SIGN_OUT_USER_FAILED';
export const AUTH_CLEAN_STORE = 'AUTH_CLEAN_STORE';
// Save state
export const UPDATE_NEW_USER_STATE = 'UPDATE_NEW_USER_STATE';
export const UPDATE_NEW_VEHICLE_STATE = 'UPDATE_NEW_VEHICLE_STATE';
export const UPDATE_NEW_DRIVER_STATE = 'UPDATE_NEW_DRIVER_STATE';
// RESSETTING
export const RESETTING_PASSWORD_SUCCESS = 'resetting_password_success';
export const RESETTING_PASSWORD = 'resetting_password';
export const RESETTING_PASSWORD_FAILED = 'resetting_password_failed';
// OFFERS
export const OFFERS_CLEAN = 'OFFERS_CLEAN';
export const OFFERS_STOP_LISTEN_lOAD = 'OFFERS_STOP_LISTEN_LOAD';
export const OFFERS_LOAD = 'OFFERS_LOAD';
export const OFFERS_LOADED= ' OFFERS_LOADED';
export const OFFERS_LOAD_FAILED = 'OFFERS_LOAD_FAILED';
// Penalties
export const PENALTIES_CLEAN = 'PENALTIES_CLEAN';
export const PENALTIES_STOP_LISTEN_LOAD = 'PENALTIES_STOP_LISTEN_LOAD';
export const PENALTIES_LOAD = 'PENALTIES_LOAD';
export const PENALTIES_LOAD_FAIL = 'PENALTIES_LOAD_FAIL';
export const PENALTIES_LOADED = 'PENALTIES_LOADED';
// Vehicles
export const VEHICLES_ADD = 'VEHICLES_ADD';
export const VEHICLES_ADDED = 'VEHICLES_ADDED';
export const VEHICLES_ADD_FAIL = 'VEHICLES_ADD_FAIL';
export const VEHICLES_CLEAN = 'VEHICLES_CLEAN';
export const VEHICLES_STOP_LISTEN_lOAD = 'VEHICLES_STOP_LISTEN_LOAD';
export const VEHICLES_LOAD = 'VEHICLES_LOAD';
export const VEHICLES_LOADED= 'VEHICLES_LOADED';
export const VEHICLES_LOAD_FAILED = 'VEHICLES_LOAD_FAILED';
// Accidentes
export const ACCIDENT_ADD = 'ACCIDENT_ADD';
export const ACCIDENT_ADDED = 'ACCIDENT_ADDED';
export const ACCIDENT_ADD_FAIL = 'ACCIDENT_ADD_FAIL';
export const ACCIDENT_CLEAN = 'ACCIDENT_CLEAN';
// Contraofertas
export const OFFER_DRIVER_CLEAN = 'OFFER_DRIVER_CLEAN';
export const OFFER_DRIVER_ADD = 'OFFER_DRIVER_ADD';
export const OFFER_DRIVER_ADDED = 'OFFER_DRIVER_ADDED';
export const OFFER_DRIVER_ADD_FAIL = 'OFFER_DRIVER_ADD_FAIL';
export const OFFER_DRIVER_UPDATE = 'OFFER_DRIVER_UPDATE';
export const OFFER_DRIVER_UPDATED = 'OFFER_DRIVER_UPDATED';
export const OFFER_DRIVER_UPDATE_FAIL = 'OFFER_DRIVER_UPDATE_FAIL';
//PROFILES
export const PROFILE_CLEAN = 'PROFILE_CLEAN';
export const PROFILE_STOP_LISTEN_LOAD = 'PROFILE_STOP_LISTEN_LOAD';
export const PROFILE_LOAD = 'PROFILE_LOAD';
export const PROFILE_LOADED = 'PROFILE_LOADED';
export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const PROFILE_UPDATED = 'PROFILE_UPDATED';
export const PROFILE_LOAD_FAILED = 'PROFILE_LOAD_FAILED';
export const PROFILE_UPDATE_FAILED = 'PROFILE_UPDATE_FAILED';
//TRIPS
export const TRIP_LOADED = 'TRIP_LOADED';
export const TRIP_LOAD = 'TRIP_LOAD';
export const TRIP_LOAD_FAILED = 'TRIP_LOAD_FAILED';
export const TRIP_CANCELED = 'TRIP_CANCELED';
export const TRIP_CANCEL = 'TRIP_CANCEL';
export const TRIP_CANCEL_FAILED = 'TRIP_CANCEL_FAILED';
export const TRIP_STOP_LISTEN_LOAD = 'TRIP_STOP_LISTEN_LOAD';
export const TRIP_CURRENCY_LOADED = 'TRIP_CURRENCY_LOADED';
export const TRIP_CURRENCY_LOAD = 'TRIP_CURRENCY_LOAD';
export const TRIP_CURRENCY_LOAD_FAILED = 'TRIP_CURRENCY_LOAD_FAILED';
export const TRIP_CURRENCY_STOP_LISTEN_LOAD = 'TRIP_CURRENCY_STOP_LISTEN_LOAD';
export const TRIP_UPDATED = 'TRIP_UPDATED';
export const TRIP_UPDATE = 'TRIP_UPDATE';
export const TRIP_UPDATE_FAILED = 'TRIP_UPDATE_FAILED';
export const TRIP_FINISH = 'TRIP_FINISH';
export const TRIP_FINISHED = 'TRIP_FINISHED';
export const TRIP_FINISH_FAILED = 'TRIP_FINISH_FAILED';
export const TRIP_CLEAN = 'TRIP_CLEAN';
// ABOUT
export const ABOUT_LOADED = 'ABOUT_LOADED';
export const ABOUT_LOAD = 'ABOUT_LOAD';
export const ABOUT_LOAD_FAILED = 'ABOUT_LOAD_FAILED';
export const ABOUT_CLEAN = 'ABOUT_CLEAN';
